config/routes.rb
Cheerups::Application.routes.draw do
 
  resources :cheers do
    get 'page/:page', action: :index, on: :collection
    member do
      get "cheerup", to: "cheers#upvote"
      get "cheerdown", to: "cheers#downvote"
    end
  end

  root :to => "cheers#index"

  resources :relationships, only: [:create, :destroy]
  resources :promotes

  match '/ajax/users', to: 'autocomplete#users', as: :ajax

  

  devise_for :users, :controllers => {registrations: 'registrations',  omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new" 
    resources :users,  only: [:index]
    resources :users do
        member do
          get :following, :followers
        end
      end
  end

  
  
  
  

end

app/models/promote.rb
class Promote < ActiveRecord::Base
  attr_accessible :cheer_id, :status, :user_id
  belongs_to :user
  belongs_to :cheer 
end

app/controllers/promotes_controller.rb
class PromotesController < ApplicationController
  # GET /promotes
  # GET /promotes.json
  def index
    @promotes = Promote.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @promotes }
    end
  end

  # GET /promotes/1
  # GET /promotes/1.json
  def show
    @promote = Promote.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @promote }
    end
  end

  # GET /promotes/new
  # GET /promotes/new.json
  def new
    @promote = Promote.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @promote }
    end
  end

  # GET /promotes/1/edit
  def edit
    @promote = Promote.find(params[:id])
  end

  # POST /promotes
  # POST /promotes.json
  def create
    @promote = Promote.new(params[:promote])
    @promote.user_id = current_user.id
    @promote.save

    respond_to do |format|
      if @promote.save
        format.html { redirect_to @promote, notice: 'Promote was successfully created.' }
        format.json { render json: @promote, status: :created, location: @promote }
      else
        format.html { render action: "new" }
        format.json { render json: @promote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /promotes/1
  # PUT /promotes/1.json
  def update
    @promote = Promote.find(params[:id])

    respond_to do |format|
      if @promote.update_attributes(params[:promote])
        format.html { redirect_to @promote, notice: 'Promote was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @promote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /promotes/1
  # DELETE /promotes/1.json
  def destroy
    @promote = Promote.find(params[:id])
    @promote.destroy

    respond_to do |format|
      format.html { redirect_to promotes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/promotes_helper.rb
module PromotesHelper
end

app/views/promotes/_form.html.haml
= form_for @promote do |f|
  - if @promote.errors.any?
    #error_explanation
      %h2= "#{pluralize(@promote.errors.count, "error")} prohibited this promote from being saved:"
      %ul
        - @promote.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/promotes/edit.html.haml
%h1 Editing promote

= render 'form'

= link_to 'Show', @promote
\|
= link_to 'Back', promotes_path

app/views/promotes/index.html.haml
%h1 Listing promotes

%table
  %tr
    %th
    %th
    %th

  - @promotes.each do |promote|
    %tr
      %td= link_to 'Show', promote
      %td= link_to 'Edit', edit_promote_path(promote)
      %td= link_to 'Destroy', promote, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Promote', new_promote_path

app/views/promotes/new.html.haml
%h1 New promote

= render 'form'

= link_to 'Back', promotes_path

app/views/promotes/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_promote_path(@promote)
\|
= link_to 'Back', promotes_path