config/routes.rb
Cheerups::Application.routes.draw do
 
  resources :cheers do
    get 'page/:page', action: :index, on: :collection
    member do
      get "cheerup", to: "cheers#upvote"
      get "cheerdown", to: "cheers#downvote"
    end
  end

  root :to => "cheers#index"

  resources :relationships, only: [:create, :destroy]
  resources :promotes

  match '/ajax/users', to: 'autocomplete#users', as: :ajax

  

  devise_for :users, :controllers => {registrations: 'registrations',  omniauth_callbacks: "omniauth_callbacks" }

  devise_scope :user do
    get "sign_in", :to => "devise/sessions#new" 
    resources :users,  only: [:index]
    resources :users do
        member do
          get :following, :followers
        end
      end
  end

  
  
  
  

end

app/models/cheer.rb
class Cheer < ActiveRecord::Base
  acts_as_votable
  attr_accessible :cheerup, :user_id
  has_many :promotes, dependent: :destroy
  belongs_to :user
  has_many :users, through: :promotes
  default_scope -> { order('created_at DESC') }

  def cheerup_score
    self.get_upvotes.size
  end

  def cheerdown_score
    self.get_downvotes.size
  end

  def score
    cheerup = self.get_upvotes.size
    cheerdown = self.get_downvotes.size
    cheerup - cheerdown
  end
end

app/controllers/cheers_controller.rb
class CheersController < ApplicationController

  skip_before_filter :verify_authenticity_token
  
  before_filter :set_cheer, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json, :js
  
  def index
    if current_user
      @cheers = Cheer.order(:created_at).page(params[:page]).per_page(10)    # @cheers = Cheer.all
      respond_with(@cheers)
    else
      redirect_to new_user_session_path
    end
  end

  def show
    respond_with(@cheer)
  end

  def new
    @cheer = Cheer.new
    respond_with(@cheer)
  end

  def edit
  end

  def create
    @cheer = Cheer.new(params[:cheer])
    @cheer.user_id = current_user.id
    @cheer.save
    respond_with(@cheer)
  end

  def update
    @cheer.update_attributes(params[:cheer])
    respond_with(@cheer)
  end

  def destroy
    @cheer.destroy
    respond_with(@cheer)
  end

  # cheer voting upvote and downvote
  def upvote
    @cheer = Cheer.find(params[:id])
    @cheer.upvote_by current_user
    respond_to do |format|
      format.json { render :json => @cheer.cheerup_score }
    end
  end

  def downvote
    @cheer = Cheer.find(params[:id])
    @cheer.downvote_by current_user
    respond_to do |format|
     format.json { render :json => @cheer.cheerup_score }
    end
  end

  private
    def set_cheer
      @cheer = Cheer.find(params[:id])
    end
end

app/helpers/cheers_helper.rb
module CheersHelper
end

app/views/cheers/_cheer.html.haml
%li{:id => "cheer-#{cheer.id}"}
  .button_edit
    .user_section
      .image= image_tag gravatar_for(cheer.user), class: "small-avatar"
      .user= link_to cheer.user.username, user_path(cheer.user)
    .edit_section  
      .destroy{"data-id" =>cheer.id}
        = link_to "<span class=\"glyphicon glyphicon-remove\"></span>".html_safe, cheer
  .content= cheer.cheerup
  .timestamp
    Posted #{time_ago_in_words(cheer.created_at)} ago.
  .button_div
    -if cheer.promotes.present?
      -if cheer.promotes.last.status == "liked"
        %span.glyphicon.glyphicon-thumbs-up.clicked{data: {id: "#{cheer.promotes.last.id}"}}
        .score_up{:id => "score_up-#{cheer.id}"}= "#{cheer.promotes.where(status: 'liked').count}"
        %span.glyphicon.glyphicon-thumbs-down.changevotedown{data: {id: "#{cheer.promotes.last.id}"}}
        .score_down{:id => "score_down-#{cheer.id}"}= "#{cheer.promotes.where(status: 'dislike').count}"
      -else
        %span.glyphicon.glyphicon-thumbs-up.changevoteup{data: {id: "#{cheer.promotes.last.id}"}}
        .score_up{:id => "score_up-#{cheer.id}"}= "#{cheer.promotes.where(status: 'liked').count}"
        %span.glyphicon.glyphicon-thumbs-down.clicked{data: {id: "#{cheer.promotes.last.id}"}}
        .score_down{:id => "score_down-#{cheer.id}"}= "#{cheer.promotes.where(status: 'dislike').count}"
    -else
      %span.glyphicon.glyphicon-thumbs-up.newupvote{data: {id: "#{cheer.id}"}}
      .score_up{:id => "score_up-#{cheer.id}"}= "#{cheer.promotes.where(status: 'liked').count}"
      %span.glyphicon.glyphicon-thumbs-down.newdownvote{data: {id: "#{cheer.id}"}}
      .score_down{:id => "score_down-#{cheer.id}"}= "#{cheer.promotes.where(status: 'dislike').count}"
    / cheer.cheerup_score

app/views/cheers/_follow_form.html.haml
- unless current_user?(@user)
  #follow_form
    - if current_user.following?(@user)
      = render 'unfollow'
    - else
      = render 'follow'

app/views/cheers/_form.html.haml
= form_for @cheer, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :user_id, :class => 'control-label'
    .controls
      = f.number_field :user_id, :class => 'number_field'
  .control-group
    = f.label :cheerup, :class => 'control-label'
    .controls
      = f.text_field :cheerup, :class => 'text_field'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), cheers_path, :class => 'btn'

app/views/cheers/create.js.erb
$("#cheers").prepend("<%= j (render @cheer) %>");
$('#new-cheer').val('');
$('#user_cheers').prepend("<%= j (render @cheer) %>");
 

app/views/cheers/edit.html.haml
- model_class = Cheer
.page-header
  %h1=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/cheers/index.html.haml
%table.table.table-hover
%section.stats
- if current_user
  #new-cheer-input
    .image= image_tag gravatar_for(current_user), class: "small-avatar"
    %input#new-cheer{:placeholder => "What's your cheer today?", :type => "text"}/
  #cheers
    = render @cheers
  = will_paginate @cheers

app/views/cheers/index.js.haml
$('#cheers').append('#{j render(@cheers)}');
- if @cheers.next_page
  $('.pagination').replaceWith('#{j will_paginate(@cheers)}');
- else
  $('.pagination').remove();
- sleep 1

app/views/cheers/new.html.haml
- model_class = Cheer
.page-header
  %h1=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => "form"

app/views/cheers/show.html.haml
- model_class = Cheer
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:user_id) + ':'
  %br
  = @cheer.user_id
%p
  %strong= model_class.human_attribute_name(:cheerup) + ':'
  %br
  = @cheer.cheerup

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), cheers_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_cheer_path(@cheer), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), cheer_path(@cheer), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'